In [1]:
import numpy as np

In [2]:
arr = np.array([4,2,9,1])

In [3]:
sorted_arr = np.sort(arr)

In [4]:
print(sorted_arr)

[1 2 4 9]

In [5]:
arr2d = np.array([[3,1,2],[9,6,5]])

In [6]:
sorted_2d = np.sort(arr2d)

In [7]:
print(sorted_2d)

[[1 2 3]
 [5 6 9]]

In [8]:
sorted_by_column = np.sort(arr2d,axis=0)
print(sorted_by_column)

[[3 1 2]
 [9 6 5]]

In [9]:
import pandas as pd

df = pd.DataFrame({
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,20]
})

In [10]:
sorted_df = df.sort_values(by='Age')

In [11]:
print(sorted_df)

      Name  Age
2  Charlie   20
0    Alice   25
1      Bob   30

In [13]:
df.sort_values(by='Age',ascending=False)

      Name  Age
1      Bob   30
0    Alice   25
2  Charlie   20

In [15]:
df = pd.DataFrame({
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,25,30],
    'Score':[80,90,70]
})

df.sort_values(by=['Age','Score'],ascending=[False,True])

      Name  Age  Score
2  Charlie   30     70
0    Alice   25     80
1      Bob   25     90

In [16]:
df.sort_index()

      Name  Age  Score
0    Alice   25     80
1      Bob   25     90
2  Charlie   30     70

In [25]:
import numpy as np


names = np.array(['Alice:0','Bob:1','Charlie:2','Francis:3'])
scores = np.array([85,95,70,75])

In [26]:
idx = np.argsort(scores)
print(idx)

[2 3 0 1]

In [27]:
sorted_names = names[idx]

In [28]:
print(sorted_names)

['Charlie:2' 'Francis:3' 'Alice:0' 'Bob:1']

In [29]:
data = np.array([
    [1,20],
    [2,10],
    [3,15]
])

In [32]:
sorted_data = data[data[:,0].argsort()]

In [33]:
print(sorted_data)

[[ 1 20]
 [ 2 10]
 [ 3 15]]

In [34]:
s = pd.Series([3,1,2])

In [35]:
s_sorted = s.sort_values()

In [36]:
print(s_sorted)

1    1
2    2
0    3
dtype: int64

In [37]:
df = pd.DataFrame({
    'Name':['Bob','Alice','Charlie'],
    'Age':[30,25,20]
}, index=['b','a','c'])

In [38]:
df.sort_index()

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   20

In [39]:
df = pd.DataFrame({
    'Name':['Anna','Ben','Cathy','Daniel'],
    'Checkins':[10,25,15,25],
    'JoinDate':['2024-04-01','2022-09-15','2023-01-20','2022-09-15']
})

df['JoinDate'] = pd.to_datetime(df['JoinDate'])
df.sort_values(by=['Checkins','JoinDate'],ascending=[False,True])

     Name  Checkins   JoinDate
1     Ben        25 2022-09-15
3  Daniel        25 2022-09-15
2   Cathy        15 2023-01-20
0    Anna        10 2024-04-01

In [40]:
arr = np.array([2,3,2,1])
sorted_arr = np.sort(arr,kind='mergesort')
print(sorted_arr)

[1 2 2 3]

In [41]:
arr = np.array([10,5,8,7,2])

filtered = arr[arr > 5]

sorted_filtered = np.sort(filtered)

In [42]:
print(sorted_filtered)

[ 7  8 10]

In [46]:
data = np.array([
    (1,'Alice',90),
    (2,'Bob',85),
    (3,'Charlie',95)
],dtype=[('id','i4'),('name','U10'),('score','i4')])

In [47]:
sorted_data = np.sort(data,order='score')

In [48]:
print(sorted_data)

[(2, 'Bob', 85) (1, 'Alice', 90) (3, 'Charlie', 95)]

In [49]:
df = pd.DataFrame({
    'Name':['Anna','Ben','Cathy'],
    'Score':[90,95,90]
})

df['Rank']= df['Score'].rank(method='dense',ascending=False)
print(df)

    Name  Score  Rank
0   Anna     90   2.0
1    Ben     95   1.0
2  Cathy     90   2.0

In [50]:
df = pd.DataFrame({
    'Name':['Anna','Ben','Cathy'],
    'Score':[90,85,95]
})

df_filtered = df[df['Score'] > 85].sort_values(by='Score')
print(df_filtered)

    Name  Score
0   Anna     90
2  Cathy     95

In [51]:
import numpy as np

In [53]:
inventory = np.array([
    (1001,'Whey Protein',30,2500.0),
    (1002,'Creatine',50,1500.0),
    (1003,'Multivitamins',100,800.0),
    (1004,'Pre-Workout',25,2000.0),
    (1005,'Mass Gainer',15,3000.0)
],dtype=[('product_id','i4'),('name','U20'),('stock','i4'),('price','f4')])

In [54]:
print(inventory['name'])

['Whey Protein' 'Creatine' 'Multivitamins' 'Pre-Workout' 'Mass Gainer']

In [55]:
print(inventory['product_id'])

[1001 1002 1003 1004 1005]

In [56]:
print(inventory['price'])

[2500. 1500.  800. 2000. 3000.]

In [57]:
print(inventory['stock'])

[ 30  50 100  25  15]

In [58]:
low_stock = inventory[inventory['stock'] < 30 ]

In [59]:
print(low_stock)

[(1004, 'Pre-Workout', 25, 2000.) (1005, 'Mass Gainer', 15, 3000.)]

In [60]:
sorted_by_price = np.sort(inventory,order='price')
print(sorted_by_price)

[(1003, 'Multivitamins', 100,  800.) (1002, 'Creatine',  50, 1500.)
 (1004, 'Pre-Workout',  25, 2000.) (1001, 'Whey Protein',  30, 2500.)
 (1005, 'Mass Gainer',  15, 3000.)]

In [ ]:
expensive = inventory[inventory['price'] >= 2000 ]

In [ ]:
print(expensive)

[(1002, 'Creatine',  50, 1500.) (1003, 'Multivitamins', 100,  800.)
 (1004, 'Pre-Workout',  25, 2000.)]

In [66]:
cheap = inventory[inventory['price'] <= 2000 ]

In [67]:
print(cheap)

[(1002, 'Creatine',  50, 1500.) (1003, 'Multivitamins', 100,  800.)
 (1004, 'Pre-Workout',  25, 2000.)]

In [68]:
total_value = np.sum(inventory['stock'] * inventory['price'])

In [69]:
print('Total inventory',total_value)

Total inventory 325000.0

In [71]:
df = pd.DataFrame(inventory)
print(df.sort_values(by='stock',ascending=False))

   product_id           name  stock   price
2        1003  Multivitamins    100   800.0
1        1002       Creatine     50  1500.0
0        1001   Whey Protein     30  2500.0
3        1004    Pre-Workout     25  2000.0
4        1005    Mass Gainer     15  3000.0

In [89]:
flights = np.array([
    ('PR101', 'Manila', 'Tokyo', '2025-05-11 06:00', 180),
    ('PR102', 'Tokyo', 'Manila', '2025-05-11 11:30', 200),
    ('PR201', 'Manila', 'Cebu', '2025-05-11 09:00', 90),
    ('PR202', 'Cebu', 'Manila', '2025-05-11 13:00', 85),
    ('PR301', 'Manila', 'Davao', '2025-05-11 15:00', 160)
], dtype=[
    ('flight_no', 'U10'),
    ('origin', 'U10'),
    ('destination', 'U10'),
    ('departure', 'U20'),
    ('passengers', 'i4')
])

In [73]:
print(flights['destination'])

['Tokyo' 'Manila' 'Cebu' 'Manila' 'Davao']

In [74]:
from_manila = flights[flights['origin']=='Manila']

In [75]:
print(from_manila)

[('PR101', 'Manila', 'Tokyo', '2025-05-11 06:00', 180)
 ('PR201', 'Manila', 'Cebu', '2025-05-11 09:00',  90)
 ('PR301', 'Manila', 'Davao', '2025-05-11 15:00', 160)]

In [76]:
passenger_number = flights[flights['passengers'] >= 150]

In [77]:
print(passenger_number)

[('PR101', 'Manila', 'Tokyo', '2025-05-11 06:00', 180)
 ('PR102', 'Tokyo', 'Manila', '2025-05-11 11:30', 200)
 ('PR301', 'Manila', 'Davao', '2025-05-11 15:00', 160)]

In [81]:
sorted_passenger = np.sort(flights,order='passengers')

In [82]:
print(sorted_passenger)

[('PR202', 'Cebu', 'Manila', '2025-05-11 13:00',  85)
 ('PR201', 'Manila', 'Cebu', '2025-05-11 09:00',  90)
 ('PR301', 'Manila', 'Davao', '2025-05-11 15:00', 160)
 ('PR101', 'Manila', 'Tokyo', '2025-05-11 06:00', 180)
 ('PR102', 'Tokyo', 'Manila', '2025-05-11 11:30', 200)]

In [83]:
new_flights = np.array([('PR401','Manila','Hongkong','2025-05-11 20:00',190)],dtype=flights.dtype)

In [84]:
flights = np.concatenate((flights,new_flights))

In [85]:
print(flights)

[('PR101', 'Manila', 'Tokyo', '2025-05-11 06:00', 180)
 ('PR102', 'Tokyo', 'Manila', '2025-05-11 11:30', 200)
 ('PR201', 'Manila', 'Cebu', '2025-05-11 09:00',  90)
 ('PR202', 'Cebu', 'Manila', '2025-05-11 13:00',  85)
 ('PR301', 'Manila', 'Davao', '2025-05-11 15:00', 160)
 ('PR401', 'Manila', 'Hongkong', '2025-05-11 20:00', 190)]

In [ ]:
#df['departure'] = pd.to_datetime(df['departure'])
#morning_flights = df[df['departure'].dt.hour < 12]

KeyError: 'departure'

In [91]:
count = df['destination'].value_counts()
print(count)

KeyError: 'destination'

In [92]:
patients = np.array([
    (101, 'Juan Dela Cruz', 'M', 35, '2025-05-10', True),
    (102, 'Maria Santos', 'F', 28, '2025-05-08', False),
    (103, 'Jose Rizal', 'M', 60, '2025-05-05', True),
    (104, 'Ana Reyes', 'F', 45, '2025-05-09', False),
    (105, 'Pedro Penduko', 'M', 50, '2025-05-11', True)
], dtype=[
    ('id', 'i4'),
    ('name', 'U20'),
    ('gender', 'U1'),
    ('age', 'i4'),
    ('admission_date', 'U10'),
    ('critical', '?')
])

In [93]:
print(patients['name'])

['Juan Dela Cruz' 'Maria Santos' 'Jose Rizal' 'Ana Reyes' 'Pedro Penduko']

In [94]:
male_patient = patients[patients['gender'] == 'M']

In [95]:
print(male_patient)

[(101, 'Juan Dela Cruz', 'M', 35, '2025-05-10',  True)
 (103, 'Jose Rizal', 'M', 60, '2025-05-05',  True)
 (105, 'Pedro Penduko', 'M', 50, '2025-05-11',  True)]

In [96]:
older_patients = patients[patients['age'] > 40]

In [97]:
print(older_patients)

[(103, 'Jose Rizal', 'M', 60, '2025-05-05',  True)
 (104, 'Ana Reyes', 'F', 45, '2025-05-09', False)
 (105, 'Pedro Penduko', 'M', 50, '2025-05-11',  True)]

In [98]:
sorted_by_age = np.sort(patients,order='age')

In [103]:
print(pd.DataFrame(sorted_by_age))

    id            name gender  age admission_date  critical
0  102    Maria Santos      F   28     2025-05-08     False
1  101  Juan Dela Cruz      M   35     2025-05-10      True
2  104       Ana Reyes      F   45     2025-05-09     False
3  105   Pedro Penduko      M   50     2025-05-11      True
4  103      Jose Rizal      M   60     2025-05-05      True

In [104]:
critical_patients = patients[patients['critical']]
print(pd.DataFrame(critical_patients))

    id            name gender  age admission_date  critical
0  101  Juan Dela Cruz      M   35     2025-05-10      True
1  103      Jose Rizal      M   60     2025-05-05      True
2  105   Pedro Penduko      M   50     2025-05-11      True

In [105]:
orders = np.array([
    (201, 'Burger', 2, 150.0, 'Served'),
    (202, 'Pizza', 1, 300.0, 'Preparing'),
    (203, 'Pasta', 3, 200.0, 'Served'),
    (204, 'Salad', 1, 120.0, 'Cancelled'),
    (205, 'Fries', 4, 80.0, 'Preparing')
], dtype=[
    ('order_id', 'i4'),
    ('item', 'U20'),
    ('quantity', 'i4'),
    ('price_per_item', 'f4'),
    ('status', 'U10')
])

In [109]:
print(pd.DataFrame(orders))

   order_id    item  quantity  price_per_item     status
0       201  Burger         2           150.0     Served
1       202   Pizza         1           300.0  Preparing
2       203   Pasta         3           200.0     Served
3       204   Salad         1           120.0  Cancelled
4       205   Fries         4            80.0  Preparing

In [111]:
preparing_orders = orders[orders['status']=='Preparing']
print(pd.DataFrame(preparing_orders))

   order_id   item  quantity  price_per_item     status
0       202  Pizza         1           300.0  Preparing
1       205  Fries         4            80.0  Preparing

In [112]:
total_per_order = orders['quantity'] * orders['price_per_item']

In [113]:
print(total_per_order)

[300. 300. 600. 120. 320.]

In [114]:
df = pd.DataFrame(orders)
df['total_price'] = df['quantity'] * df['price_per_item']

In [115]:
print(df[['order_id','item','total_price','status']])

   order_id    item  total_price     status
0       201  Burger        300.0     Served
1       202   Pizza        300.0  Preparing
2       203   Pasta        600.0     Served
3       204   Salad        120.0  Cancelled
4       205   Fries        320.0  Preparing

In [117]:
served_count = np.sum(orders['status']== 'Served')

In [118]:
print('Served order',served_count)

Served order 2